ARG NODE_VERSION=18
FROM webcpy1234/chatbot-base:0.1

ENV NODE_ENV=production
RUN set -eux; \
    npm install -g wx-voice && \
	npm install -g --omit=dev @chat-bot/cli --ignore-scripts && \
	npm rebuild --prefix=/usr/local/lib/node_modules/@chat-bot/cli sqlite3 && \
	rm -rf /usr/local/lib/node_modules/@chat-bot/cli/node_modules/@chat-bot/editor-ui/node_modules && \
	rm -rf /root/.npm

COPY docker-entrypoint.sh /

RUN \
	mkdir .chatbot && \
	chown node:node .chatbot
ENV SHELL /bin/sh
USER node
ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]
