ARG NODE_VERSION=18

FROM node:${NODE_VERSION}-alpine as builder

RUN apk add --no-cache ffmpeg
RUN apk add --update tini tzdata libc-dev
RUN apk add --no-cache make
RUN apk add --no-cache gcc
RUN apk add --no-cache build-base

ENV TZ=Asia/Shanghai

COPY .npmrc /usr/local/etc/npmrc
RUN npm install -g pnpm@8.14.3

# Cleanup
RUN	rm -rf /lib/apk/db /var/cache/apk/ /tmp/* /root/.npm /root/.cache/node /opt/yarn*

FROM node:${NODE_VERSION}-alpine
COPY --from=builder / /


WORKDIR /home/node
EXPOSE 7001/tcp
EXPOSE 1883/tcp