ARG NODE_VERSION=18

FROM node:${NODE_VERSION}-alpine as builder

RUN apk add --no-cache ffmpeg tini

COPY .npmrc /usr/local/etc/npmrc
RUN npm install -g npm@9.9.2 wx-voice@0.2.1


WORKDIR /tmp
COPY package.json ./
RUN corepack enable && corepack prepare --activate

# Cleanup
RUN	rm -rf /lib/apk/db /var/cache/apk/ /tmp/* /root/.npm /root/.cache/node /opt/yarn*

FROM node:${NODE_VERSION}-alpine
COPY --from=builder / /


WORKDIR /home/node
EXPOSE 7001/tcp